# Generated by Django 4.2.2 on 2023-06-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mobile_App', '0002_partipolitique_fondateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='partipolitique',
            name='nom',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
